<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/jquery.kumbiaphp.js\">";?></script>

<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/jQueryUi/Jquery-ui.min.js\">";?></script>

<?php /*echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.core.js\">"; ?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.widget.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.tabs.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.position.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.dialog.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.mouse.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.draggable.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.droppable.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.sortable.js\">";?></script>
<?php */echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/ui/jquery.ui.timepicker.js?v=0.3.2\">";?></script>
<?php  echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/bootstrap.min.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/morris/morris.min.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/sparkline/jquery.sparkline.min.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/jvectormap/jquery-jvectormap-world-mill-en.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/knob/jquery.knob.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/daterangepicker/moment.min.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/daterangepicker/daterangepicker.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/datepicker/bootstrap-datepicker.js\">";?></script>
<?php 
echo Tag::js('jquery/plugins/fullcalendar/fullcalendar.min');
echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/slimScroll/jquery.slimscroll.min.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/iCheck/icheck.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/plugins/fastclick/fastclick.js\">";?></script>
<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/AdminLTE/app.js\">";?></script>

<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/jquery.PrintArea.js\">";?></script>
<script src="http://code.jquery.com/jquery-migrate-1.4.1.js"></script>

<?php echo "<script src=\"", PUBLIC_PATH, "javascript/jquery/jquery.autocomplete.js\">";?></script>

<?php echo "<script src=\"", PUBLIC_PATH, "javascript/global.js\"></script>";?>
