<div class="page-header">
    <h1>Crear nuevo Acabado</h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('proestadosprocesos.id') ?>
<div class="control-group">
    <label for="usuario_login">Nombre del Estado* : </label>
    <div class="controls">
        <?php echo Form::text('proestadosprocesos.nombre') ?>
    </div>
</div>
<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
