
<div class="page-header">
    <h1>Listado de Estados de Procesos</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php
Table::headers('id', 'Nombre de Estado');
Table::headers('Estado', 'Editar','Eliminar');
Table::fields('id', 'nombre');
Table::imgLink('figuras/circulo_verde.png|figuras/circulo_rojo.png', 'admin/proestadosprocesos/desactivar|admin/proestadosprocesos/activar', '', 'activo');
Table::imgLink('figuras/editar.png', 'admin/proestadosprocesos/editar');
Table::imgLinkConfirm('figuras/eliminar.png', 'admin/proestadosprocesos/eliminar', '', '¿Realmente desea Eliminar este Estado?');
echo Table::create($proestadosprocesos, 'class="table table-bordered table-striped"');
?>
<div class="form-actions">
    <?php echo Html::linkAction("crear", 'Crear Nuevo Estado','class="btn btn-primary"') ?>
</div>
