<?php if($id==0){?>
<div class="page-header">
    <h1>Crear Cuenta Principal del Plan Contable</h1>
</div>      
<?php } 
View::content() ?>
<?php echo Form::open(NULL, 'post', 'role="form"') ?>
<?php echo Form::hidden('cuentas.id') ?>
<div class="form-group">
    <label class="form-label">Codigo de la Cuenta* : </label>
    <div class="forms">
        <?php echo Form::text('cuentas.codigo') ?>
    </div>
</div>
<div class="form-group">
    <label class="form-label">Descripcion* : </label>
    <div class="forms">
        <?php echo Form::text('cuentas.descripcion') ?>
    </div>
</div>

<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
