<style>
.row-fluid .span1 {
display: inline-block !important;
float: none !important;
}
</style>
<div class="box-header">
    <h1>Recursos por Agregar al Sistema
        
    </h1>
</div>
<div class="box-body">
    
<?php echo Form::open() ?>
    <div class="form-actions">
        <?php echo Form::submit('Guardar Nuevos Recursos', 'name="guardar" class="btn btn-primary"') ?> 
        <?php echo Html::linkAction('', 'Volver', 'class="btn pull-right"') ?>
        <?php echo Html::linkAction('crear', 'Crear Recurso', 'class="btn btn-primary"') ?>
    </div>
 <?php //print_r($recursos)?>
<?php View::content() ?>
        <table width="100%" id="tblTabla" border="0" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="span4">Datos del Recurso</th>
                    <th>Descripci&oacute;n</th>
                    <th>Activo</th>
                    <th>Agregar</th>
                </tr>
            </thead>
            <tbody>

        <?php 
		foreach ($recursos->items as $index => $e) :
		++$index ;?>
            <tr>
                <td>
                    <ul class="unstyled">
                        <li>
                            <strong>Recurso :</strong> <?php echo $e['recurso'] ?>
                        </li>
                        <li>
                            <strong> Modulo :</strong> <?php echo $e['modulo'] ?>
                        </li>
                        <li>
                            <strong>Controlador :</strong> <?php echo $e['controlador'] ?>
                        </li>
                        <li>
                            <strong>Accion :</strong> <?php echo $e['accion'] ?>
                        </li>
                    </ul>
                </td>
                <td>
                <?php echo Form::textarea("descripcion.$index", 'class="span6"') ?>
            </td>
            <td class="s1">
                <?php echo Form::radio("activo.$index", '1', NULL, TRUE) ?> Si <br/>
                <?php echo Form::radio("activo.$index", '0') ?> No
            </td>
            <td class="s1">
                <?php echo Form::check("check.$index", $index) ?>
            </td>
        </tr>
        <?php endforeach ?>
            </tbody>
        </table>
<?php View::partial('paginators/bootstrap', false, array('page' => $recursos, 'url' => Router::get('controller_path') . '/escaner'));?>
<?php echo Form::close()  ?>
</div>
<div class="box-footer">
    
</div>
