<div class="box-header">
    <h1 class="box-title">Crear Empresa</h1>
</div>
<div class="box-body">    
    <?php View::content() ?>
    <?php echo Form::open(NULL, 'post', 'role="form" class="form-horizontal "') ?>
    <?php echo Form::hidden('aclempresas.id') ?>
    <div class="form-group">
        <label class="form-label col-sm-2">Nombre de la Empresa* : </label>
        <div class="col-sm-8"><?php echo Form::text('aclempresas.nombre','class="form-control"') ?></div>            
    </div>
    <div class="form-group">
        <label class="form-label col-sm-2">Razon Social* : </label>
        <div class="col-sm-8"><?php echo Form::text('aclempresas.razonsocial','class="form-control"') ?></div>
            
        
    </div>
    <div class="form-group">
        <label class="form-label col-sm-2">Direccion* : </label>
        <div class="col-sm-8"><?php echo Form::text('aclempresas.direccion','class="form-control"') ?></div>      
    </div>
    <div class="form-group">
        <label class="form-label col-sm-2">Ruc* : </label>
        <div class="col-sm-8"><?php echo Form::text('aclempresas.ruc','class="form-control"') ?></div>
    </div>
    <div class="form-group">
        <label class="form-label col-sm-2">Movimiento de la Empresa* :</label>
        <div class="col-sm-8"><?php echo Form::text('aclempresas.detalle','class="form-control"') ?></div>
    </div>
    <div class="form-group">
        <label class="form-label col-sm-2">Telefono Fijo* : </label>
        <div class="col-sm-8"><?php echo Form::text('aclempresas.telefonos','class="form-control"') ?></div>
    </div>
    <div class="form-group">
        <label class="form-label col-sm-2">Fax* : </label>
        <div class="col-sm-8"><?php echo Form::text('aclempresas.telefonos1','class="form-control"') ?></div>
           
    </div>
    <div class="form-group">
        <label class="form-label col-sm-2">Celular/Movil* : </label>
        <div class="col-sm-8"><?php echo Form::text('aclempresas.telefonos2','class="form-control"') ?></div>
    </div>    
</div>
<div class="box-footer">
    <div class="form-actions pull-right">
        <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
        <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
    <?php echo Form::close() ?>
</div>