<div class="page">
    <h1 class="page-header">Crear Empresa</h1>
     
    <?php View::content() ?>
    <?php echo Form::open(NULL, 'post', 'role="form"') ?>
    <?php echo Form::hidden('aclempresas.id') ?>
    <div class="form-group">
        <label>Nombre de la Empresa* : </label>
            <?php echo Form::text('aclempresas.nombre','class="form-control"') ?>
    </div>
    <div class="form-group">
        <label class="form-label">Razon Social* : </label>
        
            <?php echo Form::text('aclempresas.razonsocial','class="form-control"') ?>
        
    </div>
    <div class="form-group">
        <label class="form-label">Direccion* : </label>
        
            <?php echo Form::text('aclempresas.direccion','class="form-control"') ?>
        
    </div>
    <div class="form-group">
        <label class="form-label">Ruc* : </label>
        
            <?php echo Form::text('aclempresas.ruc','class="form-control"') ?>
        
    </div>
    <div class="form-group">
         <label class="form-label">Movimiento de la Empresa* : </label>
        
            <?php echo Form::text('aclempresas.detalle','class="form-control"') ?>
        
    </div>
    <div class="form-group">
         <label class="form-label">Telefono Fijo* : </label>
        
            <?php echo Form::text('aclempresas.telefonos','class="form-control"') ?>
        
    </div>
    <div class="form-group">
         <label class="form-label">Fax* : </label>
        
           <?php echo Form::text('aclempresas.telefonos1','class="form-control"') ?>
        
    </div>
    <div class="form-group">
         <label class="form-label">Celular/Movil* : </label>
        
            <?php echo Form::text('aclempresas.telefonos2','class="form-control"') ?>
        
    </div>
    <div class="form-actions">
        <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
        <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
    <?php echo Form::close() ?>
</div> 