<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>INTRA</b>NET</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Seleccione una aplicacion </p>
    <div class="social-auth-links text-center">
      <p>-***-</p>
  		<?php echo Html::link('apps/index/bienvenida','Sistema de historias',array('class'=>"list-group-item")) ?>

    </div>
  </div>
  <!-- /.form-box -->
</div>
