<div class="slider jumbotron">
        <div class="container">
            <div class="col-md-6">
                <div class="slider-left">
                    <h2>Discover a new way to be more productive</h2>
                    <a href=""><button class="btn btn-default">Get in touch</button></a>
                </div>
            </div>
            <div class="col-md-offset-2 col-md-4">
                <div class="slider-right">
                    <form action="" class="join-now">
                        <h2 class="text-center">Get Started</h2>
                        <div class="input-group"><input type="text" class="form-control" placeholder="Full Name" name="full-name"></div>
                        <div class="input-group"><input type="email" class="form-control" placeholder="Email Address" name="email"></div>
                        <small class="text-center">I agree to the terms & condition</small>
                        <div class="text-center">
                            <button class="btn btn-join-now" type="submit">Join Now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>INTRA</b>NET</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Seleccione una aplicacion </p>
    <div class="social-auth-links text-center">
      <p>-***-</p>
  		<?php echo Html::link('apps/index/bienvenida','Sistema de historias',array('class'=>"list-group-item")) ?>

    </div>
  </div>
  <!-- /.form-box -->
</div>
