<div class="register-box">
  <div class="register-logo">
    <a href="../../index2.html"><b>INTRA</b>NET</a>
  </div>

  <div class="register-box-body">
    <p class="login-box-msg">Seleccione una aplicacion </p>
    <div class="social-auth-links text-center">
      <p>- OR -</p>
        <?php echo Html::link('admin/usuarios', 'Administración',array('class'=>"list-group-item")) ?>
  		<?php echo Html::link('santapatricia/index/bienvenida','Santa Patricia',array('class'=>"list-group-item")) ?>
  		<?php echo Html::link('santacarmela/index/bienvenida', 'Santa Carmela',array('class'=>"list-group-item")) ?>

    </div>
  </div>
  <!-- /.form-box -->
</div>
