<?php View::content();?>
<div class="page-header">
<h1><?php echo ucwords("$model"),": <span>$action_name</span>" ?></h1>
</div>
<div class="page">
<?php ModelForm::create($$model)?>

<div class="form-actions">
	<a href="../" class="btn">Listado</a>
</div>
<?php //View::partial('editors/tinymce') // ya veremos si incluimos algun wysiwyg?>
</div>

<script>
    $(function(){
        $('form.scaffold :submit').addClass("btn btn-primary");
    });
</script>