<?php //Tag::css('scaffold')?>
<?php View::content()?>
<div class="box-header">
    <h1><?php echo ucwords("$model"), ": <span>$action_name</span>" ?></h1>
</div>

<div class="form-actions">
	 <?php echo Html::linkAction("crear/", 'Crear registro', 'class=" primary btn"') ?>
</div>
<div class="box-body">
    <?php if ($results->items) : ?>
    <table class="table bordered-table">
        <thead>
            <tr>
        <?php foreach ($columns_view as $field) : ?>
            <th><?php echo (current($results->items)->get_alias($field))?></th>
        <?php endforeach?>
    	<th>Acciones</th>
        </tr></thead>
    	<tbody>
        <?php foreach ($results->items as $item) : ?>
            <tr>
                <?php foreach ($columns_view as $field) : ?>
                <td><?php eh($item->$field)?></td>
                <?php endforeach?>
    			<td>
    			<?php echo Html::linkAction("ver/$item->id",Html::img("figuras/ver.png",'Editar','style="width: 20px;margin-left:10px;margin-right:10px;"'),'')?> |
    			<?php echo Html::linkAction("editar/$item->id",Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:10px;margin-right:10px;"'),'')?> |
    			<?php echo Html::linkAction("borrar/$item->id",Html::img("figuras/eliminar.png",'Eliminar','style="width: 20px;margin-left:10px;margin-right:10px;"'), 'onclick="return confirm(\'¿Está seguro?\')"')?>
    			</td>
            </tr>
        <?php endforeach?>
    	</tbody>
    </table>
    <?php View::partial('paginators/bootstrap', false, array('page' => $results ,'url' => Router::get('controller_path').'/index')); ?>

    <?php else : // Si no hay items?>
    <h2>No hay ningún registro</h2>
    <?php endif ?>

    <?php //var_dump($results)?>
</div>
<div class="box-footer">
</div>