
<?php View::content()?>

<?php if($result) : ?>
<div class="page-header">
	<h1><?php echo ucwords("$model"),": <span>$action_name</span>" ?></h1>
</div>
<div class="page">
	<ul>
	<?php foreach ($result->fields as $field) : ?>
		<li><strong><?php echo $result->alias[$field]?> :</strong>  <?php eh($result->$field) ?></li>
	<?php endforeach ?>
	</ul>

	<div class="actions">
		<a href="../">Listado</a>
		<a href="../crear/">Crear registro</a>
		<a href="../editar/<?php echo $result->id?>">Editar</a>
		<a class="del" title="¿Seguro que quiere borrar?" href="../borrar/<?php echo $result->id?>" onclick="return confirm('¿Está seguro?');">Borrar</a>
	</div>
</div>
<?php else : ?>
	<?php header("HTTP/1.0 404 Not Found")?>
<div class="page-header">	<h1>No existe</h1> </div>
	<div class="actions">
		<a href="../">Listado</a>
		<a href="../crear/">Crear registro</a>
	</div>
<?php endif ?>

