<div class="page-header">
    <h1>fffff<?php if(empty($titulo)){echo ucwords("$model"), ": <span>$action_name</span>";}else{echo $titulo;}?></h1>
</div>
<?php View::content() ?>
<div class="form-actions">
    <?php echo Html::linkAction("crear/", 'Crear registro', 'class=" primary btn"') ?>
</div>
<div class="page">
<?php
Table::headers('Ver', 'Editar', 'Eliminar');
//Table::imgLink('figuras/circulo_verde.png|figuras/circulo_rojo.png', $module_name.'/'.$controller_name.'/desactivar|'.$module_name.'/'.$controller_name.'/activar', '', 'activo');
Table::imgLink('figuras/ver.png', Router::get('controller_path') . '/ver');
Table::imgLink('figuras/editar.png', Router::get('controller_path') . '/editar');
Table::imgLinkConfirm('figuras/eliminar.png', Router::get('controller_path') . '/borrar');
echo Table::create($results, 'class="table zebra-striped bordered-table"');
?>
</div>