<div class="box-header">
    <h1 class="box-title" >Configuraci&oacute; General</h1>
</div>
<div class="box-body">
    <?php View::content() ?>
    <?php echo Form::open(NULL, 'post', 'role="form" class="form-horizontal"') ?>
    <div class="form-group">
        <label for="config_name" class="col-sm-2 control-label">T&iacute;tulo del Proyecto : </label>
        <div class="col-sm-8">
            <?php echo Form::text('config.name','class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_production" class="col-sm-2 control-label">Proyecto en Producci&oacute;n : </label>        
        <div class="col-sm-8">
            <?php echo Form::select('config.production', array('On' => 'Si', 'Off' => 'No'),'class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_dbdate" class="col-sm-2 control-label">Formato de Fechas : </label>
        <div class="col-sm-8">
            <?php echo Form::text('config.dbdate','class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_debug" class="col-sm-2 control-label">Debug : </label>
        <div class="col-sm-8">
            <?php echo Form::select('config.debug', array('On' => 'Si', 'Off' => 'No'),'class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_log_exceptions" class="col-sm-2 control-label">Mostrar Excepciones : </label>
        <div class="col-sm-8">
            <?php echo Form::select('config.log_exceptions', array('On' => 'Si', 'Off' => 'No'),'class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_charset" class="col-sm-2 control-label">Codificaci&oacute;n de Caracteres : </label>
        <div class="col-sm-8">
            <?php echo Form::text('config.charset','class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_cache_driver" class="col-sm-2 control-label">Driver de Cache : </label>
        <div class="col-sm-8">
            <?php echo Form::text('config.cache_driver','class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_minimo_clave" class="col-sm-2 control-label">Caracteres M&iacute;nimo Clave : </label>
        <div class="col-sm-8">
            <?php echo Form::text('config.minimo_clave','class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_guardar_auditorias" class="col-sm-2 control-label">Auditorias Activa : </label>
        <div class="col-sm-8" >
            <?php echo Form::select('config.guardar_auditorias', array('On' => 'Si', 'Off' => 'No'),'class="form-control"') ?>
        </div>
    </div>
    <div class="form-group">
        <label for="config_guardar_auditorias" class="col-sm-2 control-label">Intentos de Acceso : </label>
        <div class="col-sm-8">
            <?php echo Form::select('config.intentos_acceso', array(1 => 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),'class="form-control"') ?>
        </div>
    </div>
</div>
<div class="box-footer">
    <div class="form-actions pull-right">
        <?php echo Form::submit('Guardar Configuración', 'class="btn btn-primary"') ?>
    </div>
</div>
<?php echo Form::close() ?>
